### ISSUE TITLE
How to add new OPDS1 entry?

### ISSUE THREAD

**Issue by Rom888** [edrlab/r2-opds-js#8]
I am trying to use this package to modify existing OPDS1 xml.
```
const xmlStr = await fs.readFile('files/open.xml', { encoding: 'utf-8' });
const xmlDom = new xmldom.DOMParser().parseFromString(xmlStr, 'text/xml');
if (!xmlDom || !xmlDom.documentElement) {
  console.log('empty xmlDom');
}
const feed = xmlDom.getElementsByTagName('feed');
```
What is the right way to create and add a new entry to and existing feed?
I don't think this is the best way:
```
const feed = xmlDom.getElementsByTagName('feed');
const newEntry = xmlDom.createElement('entry');
const titleNode = xmlDom.createElement('title');
newEntry.appendChild(titleNode);
const titleText = xmlDom.createTextNode('Title text...');
titleNode.appendChild(titleText);
newEntry.appendChild(titleNode);
feed[0].appendChild(newEntry);
```

**Comment by danielweck** [comment]
Perhaps this code snippet can help:
https://github.com/readium/r2-opds-js/blob/ac495029194803991ebe8a2cd8b2e0ea701ceaa9/test/test.ts#L689-L703

**Comment by danielweck** [comment]
Note that OPDS1 XML support is limited to deserialization (XML to TypeScript), there is no support for serialization (TypeScript to XML).

OPDS2 JSON support is bidirectional.

**Comment by Rom888** [comment]
Thanks for replies.
I need OPDS1, because my ebook supports it, and I am not sure if it supports OPDS2.
